// <auto-generated />
using System;
using ColorGoGo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIDM3312_Final.Migrations
{
    [DbContext(typeof(ColorGoGoContext))]
    partial class ColorGoGoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ColorGoGo.Models.Artist", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistID = 1,
                            ArtistName = "Luna Martinez",
                            Bio = "Specializes in floral and botanical illustrations.",
                            Email = "luna@colorgogo.com"
                        },
                        new
                        {
                            ArtistID = 2,
                            ArtistName = "Marcus Reed",
                            Bio = "Creates fantasy and dragon-themed artwork.",
                            Email = "marcus@colorgogo.com"
                        },
                        new
                        {
                            ArtistID = 3,
                            ArtistName = "Ava Thompson",
                            Bio = "Designs minimalist and geometric patterns.",
                            Email = "ava@colorgogo.com"
                        },
                        new
                        {
                            ArtistID = 4,
                            ArtistName = "Noah Bennett",
                            Bio = "Focuses on wildlife and nature scenes.",
                            Email = "noah@colorgogo.com"
                        },
                        new
                        {
                            ArtistID = 5,
                            ArtistName = "Sophia Kim",
                            Bio = "Creates mandala and meditation art.",
                            Email = "sophia@colorgogo.com"
                        });
                });

            modelBuilder.Entity("ColorGoGo.Models.ColoringBook", b =>
                {
                    b.Property<int>("ColoringBookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ColoringBookID");

                    b.HasIndex("ArtistID");

                    b.ToTable("ColoringBooks");

                    b.HasData(
                        new
                        {
                            ColoringBookID = 1,
                            ArtistID = 1,
                            BookTitle = "Blooming Gardens",
                            IsActive = true,
                            Price = 12.99m,
                            Theme = "Floral"
                        },
                        new
                        {
                            ColoringBookID = 2,
                            ArtistID = 1,
                            BookTitle = "Wildflowers Collection",
                            IsActive = true,
                            Price = 14.99m,
                            Theme = "Floral"
                        },
                        new
                        {
                            ColoringBookID = 3,
                            ArtistID = 1,
                            BookTitle = "Botanical Bliss",
                            IsActive = true,
                            Price = 11.99m,
                            Theme = "Plants"
                        },
                        new
                        {
                            ColoringBookID = 4,
                            ArtistID = 1,
                            BookTitle = "Garden Escape",
                            IsActive = true,
                            Price = 13.50m,
                            Theme = "Nature"
                        },
                        new
                        {
                            ColoringBookID = 5,
                            ArtistID = 1,
                            BookTitle = "Petal Patterns",
                            IsActive = true,
                            Price = 10.99m,
                            Theme = "Patterns"
                        },
                        new
                        {
                            ColoringBookID = 26,
                            ArtistID = 1,
                            BookTitle = "Floral Fantasy",
                            IsActive = true,
                            Price = 15.99m,
                            Theme = "Floral"
                        },
                        new
                        {
                            ColoringBookID = 27,
                            ArtistID = 1,
                            BookTitle = "Botanical Dreams",
                            IsActive = true,
                            Price = 14.50m,
                            Theme = "Plants"
                        },
                        new
                        {
                            ColoringBookID = 28,
                            ArtistID = 1,
                            BookTitle = "Garden Serenity",
                            IsActive = true,
                            Price = 13.75m,
                            Theme = "Nature"
                        },
                        new
                        {
                            ColoringBookID = 29,
                            ArtistID = 1,
                            BookTitle = "Petal Power",
                            IsActive = true,
                            Price = 12.25m,
                            Theme = "Patterns"
                        },
                        new
                        {
                            ColoringBookID = 30,
                            ArtistID = 1,
                            BookTitle = "Floral Whimsy",
                            IsActive = true,
                            Price = 11.50m,
                            Theme = "Floral"
                        },
                        new
                        {
                            ColoringBookID = 6,
                            ArtistID = 2,
                            BookTitle = "Dragon Realms",
                            IsActive = true,
                            Price = 15.99m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 7,
                            ArtistID = 2,
                            BookTitle = "Mystic Creatures",
                            IsActive = true,
                            Price = 16.99m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 8,
                            ArtistID = 2,
                            BookTitle = "Knight Adventures",
                            IsActive = true,
                            Price = 13.99m,
                            Theme = "Medieval"
                        },
                        new
                        {
                            ColoringBookID = 9,
                            ArtistID = 2,
                            BookTitle = "Legends & Lore",
                            IsActive = true,
                            Price = 17.50m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 10,
                            ArtistID = 2,
                            BookTitle = "Mythical Worlds",
                            IsActive = true,
                            Price = 18.99m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 31,
                            ArtistID = 2,
                            BookTitle = "Dragon Dreams",
                            IsActive = true,
                            Price = 16.50m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 32,
                            ArtistID = 2,
                            BookTitle = "Mystic Beasts",
                            IsActive = true,
                            Price = 17.25m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 33,
                            ArtistID = 2,
                            BookTitle = "Knight's Quest",
                            IsActive = true,
                            Price = 14.75m,
                            Theme = "Medieval"
                        },
                        new
                        {
                            ColoringBookID = 34,
                            ArtistID = 2,
                            BookTitle = "Legends Unleashed",
                            IsActive = true,
                            Price = 18.50m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 35,
                            ArtistID = 2,
                            BookTitle = "Mythical Realms",
                            IsActive = true,
                            Price = 19.99m,
                            Theme = "Fantasy"
                        },
                        new
                        {
                            ColoringBookID = 11,
                            ArtistID = 3,
                            BookTitle = "GeoShapes",
                            IsActive = true,
                            Price = 9.99m,
                            Theme = "Geometric"
                        },
                        new
                        {
                            ColoringBookID = 12,
                            ArtistID = 3,
                            BookTitle = "Modern Lines",
                            IsActive = true,
                            Price = 10.50m,
                            Theme = "Minimalist"
                        },
                        new
                        {
                            ColoringBookID = 13,
                            ArtistID = 3,
                            BookTitle = "Abstract Forms",
                            IsActive = true,
                            Price = 12.00m,
                            Theme = "Abstract"
                        },
                        new
                        {
                            ColoringBookID = 14,
                            ArtistID = 3,
                            BookTitle = "Symmetry Art",
                            IsActive = true,
                            Price = 11.25m,
                            Theme = "Patterns"
                        },
                        new
                        {
                            ColoringBookID = 15,
                            ArtistID = 3,
                            BookTitle = "Line Harmony",
                            IsActive = true,
                            Price = 9.50m,
                            Theme = "Minimalist"
                        },
                        new
                        {
                            ColoringBookID = 36,
                            ArtistID = 3,
                            BookTitle = "GeoPatterns",
                            IsActive = true,
                            Price = 10.99m,
                            Theme = "Geometric"
                        },
                        new
                        {
                            ColoringBookID = 37,
                            ArtistID = 3,
                            BookTitle = "Modern Artistry",
                            IsActive = true,
                            Price = 11.75m,
                            Theme = "Minimalist"
                        },
                        new
                        {
                            ColoringBookID = 38,
                            ArtistID = 3,
                            BookTitle = "Abstract Wonders",
                            IsActive = true,
                            Price = 13.50m,
                            Theme = "Abstract"
                        },
                        new
                        {
                            ColoringBookID = 39,
                            ArtistID = 3,
                            BookTitle = "Symmetry Magic",
                            IsActive = true,
                            Price = 12.25m,
                            Theme = "Patterns"
                        },
                        new
                        {
                            ColoringBookID = 40,
                            ArtistID = 3,
                            BookTitle = "Line Artistry",
                            IsActive = true,
                            Price = 10.75m,
                            Theme = "Minimalist"
                        },
                        new
                        {
                            ColoringBookID = 16,
                            ArtistID = 4,
                            BookTitle = "Forest Friends",
                            IsActive = true,
                            Price = 14.99m,
                            Theme = "Wildlife"
                        },
                        new
                        {
                            ColoringBookID = 17,
                            ArtistID = 4,
                            BookTitle = "Ocean Wonders",
                            IsActive = true,
                            Price = 15.49m,
                            Theme = "Sea Life"
                        },
                        new
                        {
                            ColoringBookID = 18,
                            ArtistID = 4,
                            BookTitle = "Safari Adventure",
                            IsActive = true,
                            Price = 16.25m,
                            Theme = "Animals"
                        },
                        new
                        {
                            ColoringBookID = 19,
                            ArtistID = 4,
                            BookTitle = "Mountain Majesty",
                            IsActive = true,
                            Price = 13.75m,
                            Theme = "Nature"
                        },
                        new
                        {
                            ColoringBookID = 20,
                            ArtistID = 4,
                            BookTitle = "Bird Paradise",
                            IsActive = true,
                            Price = 12.49m,
                            Theme = "Birds"
                        },
                        new
                        {
                            ColoringBookID = 41,
                            ArtistID = 4,
                            BookTitle = "Forest Magic",
                            IsActive = true,
                            Price = 15.99m,
                            Theme = "Wildlife"
                        },
                        new
                        {
                            ColoringBookID = 42,
                            ArtistID = 4,
                            BookTitle = "Ocean Mysteries",
                            IsActive = true,
                            Price = 16.75m,
                            Theme = "Sea Life"
                        },
                        new
                        {
                            ColoringBookID = 43,
                            ArtistID = 4,
                            BookTitle = "Safari Wonders",
                            IsActive = true,
                            Price = 17.50m,
                            Theme = "Animals"
                        },
                        new
                        {
                            ColoringBookID = 44,
                            ArtistID = 4,
                            BookTitle = "Mountain Magic",
                            IsActive = true,
                            Price = 14.25m,
                            Theme = "Nature"
                        },
                        new
                        {
                            ColoringBookID = 45,
                            ArtistID = 4,
                            BookTitle = "Birds of Paradise",
                            IsActive = true,
                            Price = 13.99m,
                            Theme = "Birds"
                        },
                        new
                        {
                            ColoringBookID = 21,
                            ArtistID = 5,
                            BookTitle = "Mandala Calm",
                            IsActive = true,
                            Price = 11.99m,
                            Theme = "Mandala"
                        },
                        new
                        {
                            ColoringBookID = 22,
                            ArtistID = 5,
                            BookTitle = "Zen Circles",
                            IsActive = true,
                            Price = 10.99m,
                            Theme = "Meditation"
                        },
                        new
                        {
                            ColoringBookID = 23,
                            ArtistID = 5,
                            BookTitle = "Inner Peace Patterns",
                            IsActive = true,
                            Price = 12.75m,
                            Theme = "Mandala"
                        },
                        new
                        {
                            ColoringBookID = 24,
                            ArtistID = 5,
                            BookTitle = "Sacred Geometry",
                            IsActive = true,
                            Price = 14.25m,
                            Theme = "Spiritual"
                        },
                        new
                        {
                            ColoringBookID = 25,
                            ArtistID = 5,
                            BookTitle = "Tranquil Designs",
                            IsActive = true,
                            Price = 13.00m,
                            Theme = "Meditation"
                        },
                        new
                        {
                            ColoringBookID = 46,
                            ArtistID = 5,
                            BookTitle = "Mandala Magic",
                            IsActive = true,
                            Price = 12.99m,
                            Theme = "Mandala"
                        },
                        new
                        {
                            ColoringBookID = 47,
                            ArtistID = 5,
                            BookTitle = "Zen Patterns",
                            IsActive = true,
                            Price = 11.50m,
                            Theme = "Meditation"
                        },
                        new
                        {
                            ColoringBookID = 48,
                            ArtistID = 5,
                            BookTitle = "Inner Peace Mandalas",
                            IsActive = true,
                            Price = 13.75m,
                            Theme = "Mandala"
                        },
                        new
                        {
                            ColoringBookID = 49,
                            ArtistID = 5,
                            BookTitle = "Sacred Geometry Designs",
                            IsActive = true,
                            Price = 15.25m,
                            Theme = "Spiritual"
                        },
                        new
                        {
                            ColoringBookID = 50,
                            ArtistID = 5,
                            BookTitle = "Tranquil Mandalas",
                            IsActive = true,
                            Price = 14.00m,
                            Theme = "Meditation"
                        });
                });

            modelBuilder.Entity("ColorGoGo.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "123 Maple St, Austin, TX",
                            CustomerName = "Alice Monroe"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "456 Oak Ave, Denver, CO",
                            CustomerName = "Ben Carter"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "789 Pine Rd, Seattle, WA",
                            CustomerName = "Clara Nguyen"
                        },
                        new
                        {
                            CustomerID = 4,
                            Address = "321 Birch Blvd, Chicago, IL",
                            CustomerName = "David Kim"
                        },
                        new
                        {
                            CustomerID = 5,
                            Address = "654 Cedar Ln, Miami, FL",
                            CustomerName = "Eva Rossi"
                        });
                });

            modelBuilder.Entity("ColorGoGo.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColoringBookID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderID");

                    b.HasIndex("ColoringBookID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            ColoringBookID = 1,
                            CustomerID = 1,
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            OrderID = 2,
                            ColoringBookID = 6,
                            CustomerID = 2,
                            OrderDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1,
                            Status = 1
                        },
                        new
                        {
                            OrderID = 3,
                            ColoringBookID = 11,
                            CustomerID = 3,
                            OrderDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 5,
                            Status = 2
                        },
                        new
                        {
                            OrderID = 4,
                            ColoringBookID = 16,
                            CustomerID = 4,
                            OrderDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 3,
                            Status = 3
                        },
                        new
                        {
                            OrderID = 5,
                            ColoringBookID = 21,
                            CustomerID = 5,
                            OrderDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 4,
                            Status = 0
                        },
                        new
                        {
                            OrderID = 6,
                            ColoringBookID = 2,
                            CustomerID = 1,
                            OrderDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2,
                            Status = 1
                        },
                        new
                        {
                            OrderID = 7,
                            ColoringBookID = 7,
                            CustomerID = 2,
                            OrderDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1,
                            Status = 2
                        },
                        new
                        {
                            OrderID = 8,
                            ColoringBookID = 12,
                            CustomerID = 3,
                            OrderDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 6,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ColorGoGo.Models.ColoringBook", b =>
                {
                    b.HasOne("ColorGoGo.Models.Artist", "Artist")
                        .WithMany("ColoringBooks")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ColorGoGo.Models.Order", b =>
                {
                    b.HasOne("ColorGoGo.Models.ColoringBook", "ColoringBook")
                        .WithMany("Orders")
                        .HasForeignKey("ColoringBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColorGoGo.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColoringBook");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ColorGoGo.Models.Artist", b =>
                {
                    b.Navigation("ColoringBooks");
                });

            modelBuilder.Entity("ColorGoGo.Models.ColoringBook", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ColorGoGo.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
